<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoViz.Core\AlgoViz.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Samples\*.csx" />
  </ItemGroup>

</Project>
